import { Calendar, Clock, MapPin, ArrowRight, Share2, CalendarDays } from "lucide-react";
import { Link } from "react-router-dom";
import { useEffect, useMemo, useState } from "react";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { AnimatedSection } from "@/components/AnimatedSection";
import { usePageHero } from "@/hooks/usePageContent";
import { useSEO } from "@/hooks/useSEO";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "sonner";
import { getEventImage } from "@/lib/eventImages";
import { optimizedImageUrl } from "@/lib/imageUrl";
import { staticEvents } from "@/data/staticSiteContent";
import { semesterCalendar2026 } from "@/data/semesterCalendar2026";
import { shareItem } from "@/lib/shareLinks";

interface Event { id:string; title:string; description:string|null; event_date:string; start_time:string; end_time:string|null; location:string; category:string|null; image_url:string|null; registration_link:string|null; is_featured:boolean|null; slug?:string|null; theme?:string|null; scripture?:string|null; }
const todayKey=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`};
const eventPath=(e:Event)=>`/events/${e.slug||e.id}`;
const currentService=(e:Event):Event=>e.event_date==="2026-09-06"&&/sunday service/i.test(e.title)?{...e,title:"Sunday Service",description:"Come expectant and ready to listen to the Lord and be refreshed. We will also pray for our country, Kenya.",start_time:"7:00 AM",end_time:"12:45 PM",location:"CC Hall",category:"Sunday Service",theme:"Manifestation of the Glory of God",scripture:"Isaiah 60:1"}:e;

export default function Events(){
 const [db,setDb]=useState<Event[]>([]),[loading,setLoading]=useState(true),[filter,setFilter]=useState("all"); const today=todayKey();
 useEffect(()=>{(async()=>{try{const {data,error}=await supabase.from("events").select("id,title,description,event_date,start_time,end_time,location,category,image_url,registration_link,is_featured,slug,theme,scripture").eq("is_published",true).order("event_date");if(error)throw error;setDb((data||[]) as Event[])}catch{toast.error("Using the official semester calendar while live events reconnect.")}finally{setLoading(false)}})()},[]);
 const events=useMemo(()=>{const map=new Map<string,Event>();[...staticEvents,...semesterCalendar2026].forEach(x=>map.set(x.id,currentService(x as Event)));db.forEach(x=>{const duplicate=[...map.entries()].find(([,v])=>v.event_date===x.event_date&&v.title.toLowerCase()===x.title.toLowerCase());if(duplicate)map.delete(duplicate[0]);map.set(x.id,currentService(x))});return [...map.values()].sort((a,b)=>a.event_date.localeCompare(b.event_date))},[db]);
 const upcoming=events.filter(e=>e.event_date>=today),past=events.filter(e=>e.event_date<today).reverse(); const cats=["all",...new Set(upcoming.map(e=>e.category).filter(Boolean) as string[])]; const shown=filter==="all"?upcoming:upcoming.filter(e=>e.category===filter); const featured=upcoming.find(e=>e.is_featured)||upcoming[0];
 const hero=usePageHero("events",{title:"2026/2027 Semester Events",subtitle:"Official MKU Christian Union Semester One calendar · September–December 2026"});
 useSEO({title:"2026/2027 Semester Events",description:"Official MKU Christian Union Semester One events and gatherings for September–December 2026."});
 const cards=(items:Event[])=><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-6 max-w-7xl mx-auto">{items.map(e=><Card key={e.id} className="overflow-hidden group bg-card"><div className="aspect-square bg-muted overflow-hidden"><img src={optimizedImageUrl(getEventImage(e.category,e.image_url),{width:720,quality:76,resize:"contain"})} alt={e.title} className="w-full h-full object-contain" loading="lazy" decoding="async"/></div><div className="p-5"><div className="flex justify-between gap-2 mb-3"><Badge variant="secondary">{e.category||"Event"}</Badge><span className="text-xs text-muted-foreground">{new Date(`${e.event_date}T12:00:00`).toLocaleDateString("en-GB",{day:"numeric",month:"short",year:"numeric"})}</span></div><h3 className="font-serif text-xl font-bold mb-2">{e.title}</h3>{e.theme&&<p className="font-semibold text-primary text-sm">{e.theme}</p>}{e.scripture&&<p className="text-sm italic text-muted-foreground">{e.scripture}</p>}<p className="text-sm text-muted-foreground my-3 line-clamp-3">{e.description}</p><div className="space-y-1 text-sm text-muted-foreground"><p className="flex gap-2"><Clock className="w-4 h-4"/>{e.start_time}{e.end_time?` – ${e.end_time}`:""}</p><p className="flex gap-2"><MapPin className="w-4 h-4"/>{e.location}</p></div><div className="flex gap-2 mt-4"><Button asChild size="sm" className="flex-1"><Link to={eventPath(e)}>Details <ArrowRight className="w-4 h-4 ml-1"/></Link></Button><Button size="icon" variant="outline" onClick={()=>shareItem({kind:"event",key:e.id,title:e.title,text:`${e.title} · ${e.event_date} · ${e.start_time} · ${e.location}`,onCopied:()=>toast.success("Event link copied!")})}><Share2 className="w-4 h-4"/></Button></div></div></Card>)}</div>;
 return <div className="min-h-screen bg-background"><Header/><main><section className="relative min-h-[52vh] flex items-end overflow-hidden"><img src={optimizedImageUrl(getEventImage(featured?.category,featured?.image_url),{width:1600,quality:70,resize:"cover"})} alt="MKUCU events" className="absolute inset-0 w-full h-full object-cover"/><div className="absolute inset-0 bg-black/55"/><div className="container mx-auto px-4 relative pb-12 text-white"><Badge className="mb-4"><CalendarDays className="w-3 h-3 mr-1"/>{upcoming.length} Upcoming</Badge><h1 className="text-4xl md:text-6xl font-serif font-bold">{hero.title}</h1><p className="mt-3 text-lg text-white/85">{hero.subtitle}</p></div></section><section className="py-4 border-b"><div className="container mx-auto px-4 flex overflow-x-auto gap-2">{cats.map(c=><Button key={c} size="sm" variant={filter===c?"default":"outline"} onClick={()=>setFilter(c)} className="capitalize flex-shrink-0">{c}</Button>)}</div></section><AnimatedSection animation="fade-up"><section className="py-12"><div className="container mx-auto px-4">{loading&&<p className="text-center mb-6 text-muted-foreground">Loading live updates…</p>}{shown.length?cards(shown):<p className="text-center">No upcoming events in this category.</p>}</div></section></AnimatedSection>{past.length>0&&<section className="py-12 bg-muted/30"><div className="container mx-auto px-4"><h2 className="text-3xl font-serif font-bold mb-8">Event Archive</h2>{cards(past.slice(0,18))}</div></section>}</main><Footer/></div>
}
