import { Calendar, MapPin, Clock, ArrowRight, Share2 } from "lucide-react";
import { Link } from "react-router-dom";
import { toast } from "sonner";
import { shareItem } from "@/lib/shareLinks";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { useEffect, useState } from "react";
import { supabase } from "@/integrations/supabase/client";
import { getEventImage } from "@/lib/eventImages";
import { optimizedImageUrl } from "@/lib/imageUrl";
import { staticEvents } from "@/data/staticSiteContent";
import { semesterCalendar2026 } from "@/data/semesterCalendar2026";

interface Event { id:string; title:string; description:string|null; event_date:string; start_time:string; end_time:string|null; location:string; category:string|null; image_url:string|null; registration_link:string|null; theme?:string|null; scripture?:string|null; }
const localDateKey=()=>{const n=new Date();return `${n.getFullYear()}-${String(n.getMonth()+1).padStart(2,"0")}-${String(n.getDate()).padStart(2,"0")}`};
const canonicalize=(e:Event):Event=>e.event_date==="2026-09-06"&&e.title.toLowerCase().includes("sunday")?{...e,title:"Sunday Service",description:"Come expectant and ready to hear from the Lord and be refreshed. We will also pray for our country, Kenya.",start_time:"7:00 AM",end_time:"12:45 PM",location:"CC Hall",category:"Sunday Service",theme:"Manifestation of the Glory of God",scripture:"Isaiah 60:1"}:e;
const eventKey=(e:Event)=>`${e.event_date}|${e.title.toLowerCase().replace(/[^a-z0-9]+/g," ").trim()}`;

export const UpcomingEvents=()=>{
 const [events,setEvents]=useState<Event[]>([]); const [loading,setLoading]=useState(true);
 useEffect(()=>{(async()=>{const today=localDateKey(); const official=[...staticEvents,...semesterCalendar2026].filter(e=>e.event_date>=today).map(e=>canonicalize(e as Event)); try{const {data,error}=await supabase.from("events").select("*").gte("event_date",today).order("event_date",{ascending:true}); if(error)throw error; const merged=new Map<string,Event>(); official.forEach(e=>merged.set(eventKey(e),e)); (data||[]).map(e=>canonicalize(e as Event)).forEach(e=>{const key=eventKey(e);const base=merged.get(key);merged.set(key,base?{...base,...e,image_url:e.image_url||base.image_url,description:e.description||base.description}:e)}); setEvents([...merged.values()].sort((a,b)=>a.event_date.localeCompare(b.event_date)).slice(0,3));}catch(err){console.error(err);setEvents(official.sort((a,b)=>a.event_date.localeCompare(b.event_date)).slice(0,3));}finally{setLoading(false)}})()},[]);
 if(loading||!events.length)return null;
 return <section className="py-10 bg-background"><div className="container mx-auto px-4"><div className="text-center mb-6"><div className="inline-flex items-center gap-2 bg-accent/10 text-accent px-3 py-1.5 rounded-full mb-3"><Calendar className="w-4 h-4"/><span className="text-xs font-semibold">2026/2027 Semester Calendar</span></div><h2 className="text-2xl md:text-3xl font-serif font-bold text-foreground">Coming Up</h2></div><div className="grid grid-cols-1 md:grid-cols-3 gap-4 max-w-5xl mx-auto mb-6">{events.map(event=><Card key={event.id} className="overflow-hidden hover:shadow-lg transition-all duration-300 group border-border bg-card"><div className="relative aspect-square overflow-hidden bg-[#f5f1ed] p-2"><img src={optimizedImageUrl(getEventImage(event.category,event.image_url),{width:720,quality:76,resize:"contain"})} alt={event.title} className="w-full h-full object-contain" loading="lazy" decoding="async"/>{event.category&&<Badge className="absolute top-2 right-2 bg-primary text-primary-foreground text-xs px-2 py-0.5">{event.category}</Badge>}</div><div className="p-4"><h3 className="text-sm font-bold text-card-foreground group-hover:text-primary transition-colors mb-2">{event.title}</h3>{event.theme&&<p className="mb-1 text-xs font-semibold text-primary">{event.theme}</p>}{event.scripture&&<p className="mb-2 text-xs text-muted-foreground">{event.scripture}</p>}<div className="space-y-1.5 mb-3"><div className="flex items-center gap-2 text-xs text-muted-foreground"><Calendar className="w-3 h-3 text-primary"/><span>{new Date(`${event.event_date}T12:00:00`).toLocaleDateString("en-GB",{day:"numeric",month:"short",year:"numeric"})}</span><Clock className="w-3 h-3 text-primary ml-1"/><span>{event.start_time}{event.end_time?` – ${event.end_time}`:""}</span></div><div className="flex items-center gap-2 text-xs text-muted-foreground"><MapPin className="w-3 h-3 text-primary"/><span>{event.location}</span></div>{event.description&&<p className="pt-1 text-xs leading-5 text-muted-foreground line-clamp-3">{event.description}</p>}</div><div className="flex gap-2"><Button asChild size="sm" className="flex-1 text-xs h-9 rounded-full"><Link to={`/events/${event.id}`}>View details <ArrowRight className="w-3 h-3 ml-1"/></Link></Button><Button variant="outline" size="icon" className="h-9 w-9 rounded-full" aria-label={`Share ${event.title}`} onClick={()=>shareItem({kind:"event",key:event.id,title:event.title,text:`${event.title} — ${new Date(`${event.event_date}T12:00:00`).toLocaleDateString()} · ${event.start_time} · ${event.location}`,onCopied:()=>toast.success("Event link copied!")})}><Share2 className="w-3.5 h-3.5"/></Button></div></div></Card>)}</div><div className="text-center"><Button asChild variant="outline" size="sm"><Link to="/events">View Full Semester Calendar <ArrowRight className="w-3 h-3 ml-1"/></Link></Button></div></div></section>;
};
